version: '3.8'

services:
  furya0:
    container_name: furya0
    image: furyad
    command: start --home /furyad
    environment:
      - ID=0
      - LOG=furyad.log
    ports:
      - "1317:1317"
      - "9090:9090"
      - "26656-26657:26656-26657"
    volumes:
      - ./build/node0/simd:/furyad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  furya1:
    container_name: furya1
    image: furyad
    command: start --home /furyad
    ports:
      - "1318:1317"
      - "9091:9090"
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=furyad.log
    volumes:
      - ./build/node1/simd:/furyad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  furya2:
    container_name: furya2
    image: furyad
    command: start --home /furyad
    environment:
      - ID=2
      - LOG=furyad.log
    ports:
      - "1319:1317"
      - "9092:9090"
      - "26661-26662:26656-26657"
    volumes:
      - ./build/node2/simd:/furyad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  furya3:
    container_name: furya3
    image: furyad
    command: start --home /furyad
    environment:
      - ID=3
      - LOG=furyad.log
    ports:
      - "1320:1317"
      - "9093:9090"
      - "26663-26664:26656-26657"
    volumes:
      - ./build/node3/simd:/furyad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  furya4:
    container_name: furya4
    image: furyad
    command: start --home /furyad
    environment:
      - ID=4
      - LOG=furyad.log
    ports:
      - "1321:1317"
      - "9094:9090"
      - "26665-26666:26656-26657"
    volumes:
      - ./build/node4/simd:/furyad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.6


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/24
